### ISSUE TITLE
Unicode Encode Error: 'ascii' codec can't encode character u'\u1720'

### ISSUE THREAD

**Issue by jared703** [tomchop/volatility-autoruns#11]
Hey Tom,

I'm getting a Unicode error when using Autoruns (latest build from yesterday) with Vol 2.4 (I tried both python and precompiled versions). Image is a WinXPSP2x86 sample.

```
Volatility Foundation Volatility Framework 2.4
Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 192, in <module>
    main()
  File "/usr/local/bin/vol.py", line 183, in main
    command.execute()
  File "/home/gmucfrs/vol/volatility-2.4/volatility/commands.py", line 103, in execute
    data = self.calculate()
  File "/home/gmucfrs/vol/volatility-2.4/volatility/plugins/autoruns.py", line 521, in calculate
    self.services = self.get_services()
  File "/home/gmucfrs/vol/volatility-2.4/volatility/plugins/autoruns.py", line 311, in get_services
    service = self.parse_service_key(service)
  File "/home/gmucfrs/vol/volatility-2.4/volatility/plugins/autoruns.py", line 265, in parse_service_key
    values = {str(name): str(dat) for name, dat in self.regapi.reg_yield_values(hive_name='system', key='', given_root=service_key)}
  File "/home/gmucfrs/vol/volatility-2.4/volatility/plugins/autoruns.py", line 265, in <dictcomp>
    values = {str(name): str(dat) for name, dat in self.regapi.reg_yield_values(hive_name='system', key='', given_root=service_key)}
UnicodeEncodeError: 'ascii' codec can't encode character u'\u1720' in position 0: ordinal not in range(128)
```

Thanks,
Jared

**Comment by tomchop** [comment]
Sorry for not giving this the attention it deserves. I suspect the problem lies in `parse_service_key`, where `str` is used when it should be `unicode`. Are you still running into the same issue? Do you think you could try changing those? Unfortunately its hard for me to test without your memory sample :(

**Comment by jared703** [comment]
I haven't worked with a sample that gave me this since, but I'll test it
thoroughly it happens again. I used this plugin on all my casework and
personal analysis so I'm sure it'll shake out soon. Appreciate the response
and the tool very much.

**Comment by tomchop** [comment]
Any updates?

**Comment by jared703** [comment]
Haven't seen the error in a while. Feel free to close. I can reopen if I
see it again.

Thank you!
