### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ben4361** [tomchop/volatility-autoruns#18]
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 120, in execute
    data = self.calculate()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/community/ThomasChopitea/autoruns.py", line 519, in calculate
    self.services = self.get_services()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/community/ThomasChopitea/autoruns.py", line 309, in get_services
    service = self.parse_service_key(service)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/community/ThomasChopitea/autoruns.py", line 287, in parse_service_key
    entry = entry.replace('\x00', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by tomchop** [comment]
This was fixed a long time ago. Please update autoruns to the latest version (`git pull` should work). Out of curiosity, where did you get this version of the script?
