### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by thomaxxl** [tomchop/volatility-autoruns#7]
Volatility Foundation Volatility Framework 2.4
Traceback (most recent call last):
  File "/usr/bin/volatility", line 192, in <module>
    main()
  File "/usr/bin/volatility", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 103, in execute
    data = self.calculate()
  File "/root/ch2/volatility-autoruns/autoruns.py", line 519, in calculate
    self.services = self.get_services()
  File "/root/ch2/volatility-autoruns/autoruns.py", line 309, in get_services
    service = self.parse_service_key(service)
  File "/root/ch2/volatility-autoruns/autoruns.py", line 287, in parse_service_key
    entry = entry.replace('\x00', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by tomchop** [comment]
Hey, sorry about dropping this. Are you still getting the same errors with the latest commits?
